const PLANETS = [
  { id:"luma", name:"Luma", tag:"Leuchtende Waldsiedlung", guide:"Mio", bg:"#8ca9ff", planet:"#b6ec73", button:"#2f7a3f", sky:"#cfe5ff", ground:"#91d16c", tile:["#91d16c","#85c762"], palette:{main:"#f6b94a",dark:"#845341",light:"#fff0ad",accent:"#65b85d",glass:"#9fe3f2"} },
  { id:"coralia", name:"Coralia", tag:"Bunte Ozeankolonie", guide:"Kora", bg:"#6771d9", planet:"#ff9a98", button:"#b02d57", sky:"#bdeff2", ground:"#5fc6ba", tile:["#f0c879","#55c4c7"], palette:{main:"#ff8b88",dark:"#7d4a73",light:"#ffe1ba",accent:"#42bfc5",glass:"#a5eff4"} },
  { id:"zapp", name:"Zapp", tag:"Clevere Roboterstadt", guide:"B-8", bg:"#473a86", planet:"#b6a1f6", button:"#7254dd", sky:"#c9c3f4", ground:"#9b86c4", tile:["#9685b7","#8977aa"], palette:{main:"#8b78e6",dark:"#423879",light:"#d9d4ff",accent:"#62d6e7",glass:"#aaf5ff"} }
];

const CATALOGS = {
  luma: [
    {id:"moss-home",name:"Mooshaus",kind:"home",terrain:"land",produces:{homes:2},text:"Ein gemütliches Zuhause für zwei Waldwesen."},
    {id:"sun-field",name:"Sonnenfeld",kind:"solar",terrain:"land",produces:{energy:2},text:"Sammelt saubere Energie aus dem Sonnenlicht."},
    {id:"berry-garden",name:"Beerengarten",kind:"garden",terrain:"land",requires:{energy:1},produces:{food:2},text:"Frische Beeren für die neue Siedlung."},
    {id:"forest-path",name:"Waldweg",kind:"path",terrain:"land",text:"Verbindet deine Lieblingsorte."},
    {id:"wind-tree",name:"Baum-Windrad",kind:"wind",terrain:"land",produces:{energy:3},rarity:"selten",text:"Die Baumkrone fängt jeden Windstoß ein."},
    {id:"glass-house",name:"Glashaus",kind:"greenhouse",terrain:"land",requires:{energy:2},produces:{food:3},rarity:"selten",text:"Hier wachsen Pflanzen bei jedem Wetter."},
    {id:"maker-hut",name:"Tüftlerhütte",kind:"workshop",terrain:"land",requires:{homes:2,food:2},rarity:"legendär",text:"Eine Werkstatt voller verrückter Ideen."},
    {id:"glow-tree",name:"Leuchtbaum",kind:"tree",terrain:"land",rarity:"selten",text:"Seine Blätter leuchten in der Nacht."},
    {id:"world-tree",name:"Großer Weltenbaum",kind:"landmark",terrain:"land",requires:{homes:6,food:3,energy:3},rarity:"legendär",text:"Das Wahrzeichen einer blühenden Waldsiedlung."}
  ],
  coralia: [
    {id:"shell-home",name:"Muschelhaus",kind:"home",terrain:"land",produces:{homes:2},text:"Ein buntes Zuhause direkt an der Lagune."},
    {id:"tide-wheel",name:"Gezeitenrad",kind:"tide",terrain:"water",produces:{energy:2},text:"Macht aus Wellen saubere Energie."},
    {id:"coral-garden",name:"Korallengarten",kind:"garden",terrain:"water",requires:{energy:1},produces:{food:2},text:"Eine lebendige Unterwasser-Gärtnerei."},
    {id:"wood-dock",name:"Inselsteg",kind:"path",terrain:"any",text:"Verbindet Inseln und Wasserstationen."},
    {id:"pearl-solar",name:"Perlen-Solarfeld",kind:"solar",terrain:"land",produces:{energy:3},rarity:"selten",text:"Schimmernde Platten laden sich in der Sonne auf."},
    {id:"algae-farm",name:"Algenfarm",kind:"greenhouse",terrain:"water",requires:{energy:2},produces:{food:3},rarity:"selten",text:"Eine Farm unter einer gläsernen Kuppel."},
    {id:"light-tower",name:"Lagunen-Leuchtturm",kind:"tower",terrain:"land",requires:{homes:2,energy:2},rarity:"legendär",text:"Zeigt allen den sicheren Weg nach Hause."},
    {id:"coral-tree",name:"Riesenkoralle",kind:"tree",terrain:"water",rarity:"selten",text:"Ein farbenfroher Treffpunkt für Meereswesen."},
    {id:"pearl-palace",name:"Perlenpalast",kind:"landmark",terrain:"land",requires:{homes:6,food:3,energy:3},rarity:"legendär",text:"Das strahlende Wahrzeichen der Ozeankolonie."}
  ],
  zapp: [
    {id:"bot-home",name:"Wohnmodul",kind:"home",terrain:"land",produces:{homes:2},text:"Eine gemütliche Kapsel für kleine Roboter."},
    {id:"star-solar",name:"Sternen-Solarfeld",kind:"solar",terrain:"land",produces:{energy:2},text:"Lädt Akkus mit starkem Sternenlicht."},
    {id:"hydro-garden",name:"Hydro-Garten",kind:"garden",terrain:"land",requires:{energy:1},produces:{food:2},text:"Knackiges Gemüse aus der Raumstation."},
    {id:"neon-path",name:"Neonweg",kind:"path",terrain:"land",text:"Leuchtet den Robotern den Weg."},
    {id:"ion-turbine",name:"Ionen-Turbine",kind:"wind",terrain:"land",produces:{energy:3},rarity:"selten",text:"Fängt sogar den schwächsten Weltraumwind."},
    {id:"bio-dome",name:"Bio-Kuppel",kind:"greenhouse",terrain:"land",requires:{energy:2},produces:{food:3},rarity:"selten",text:"Ein kleiner grüner Dschungel unter Glas."},
    {id:"research-lab",name:"Forschungslabor",kind:"workshop",terrain:"land",requires:{homes:2,food:2},rarity:"legendär",text:"Hier werden neue Planetenideen erfunden."},
    {id:"signal-tree",name:"Signalantenne",kind:"tower",terrain:"land",requires:{energy:2},rarity:"selten",text:"Sendet Grüße durch die ganze Galaxie."},
    {id:"star-observatory",name:"Große Sternwarte",kind:"landmark",terrain:"land",requires:{homes:6,food:3,energy:3},rarity:"legendär",text:"Das Wahrzeichen der klügsten Roboterstadt."}
  ]
};

const STORAGE = "rechenrakete-planets-v2";
const OLD_STORAGE = "rechenrakete-planets-v1";
let saves = loadSaves();
let activeId = null;
let currentQuestion = null;
let selectedItemId = null;
let selectedPlacementId = null;
let toastTimer;
const app = document.querySelector("#app");

function readSaveData(key,fallback){try{const value=JSON.parse(localStorage.getItem(key)||"null");return Array.isArray(value)?value:fallback}catch{return fallback}}
function loadSaves() {
  let data = readSaveData(STORAGE,null);
  if (!data) data = readSaveData(OLD_STORAGE,[]);
  return data.filter(s=>s&&getPlanet(s.planetId)).map(migrateWorld);
}
function migrateWorld(s) {
  s.inventory ||= [];
  s.placements ||= [];
  const oldCount = Array.isArray(s.items) ? s.items.length : 0;
  const owned = s.inventory.length + s.placements.length;
  for (let i = owned; i < oldCount; i++) {
    const def = CATALOGS[s.planetId]?.[i % 4];
    if (def) s.inventory.push(makeItem(def));
  }
  delete s.items;
  s.totalCorrect ||= 0; s.streak ||= 0; s.stars ||= 0;
  s.day ??= Math.floor(s.totalCorrect/3);
  s.population ??= 0;
  s.tools ||= {wrench:0,can:0,hammer:0};
  s.activeEvent ||= null;
  s.nextEventDay ??= Math.max(4,s.day+3);
  s.tutorialEnabled ??= false;
  s.tutorialStep ??= s.tutorialEnabled?Math.min(s.day,4):4;
  return s;
}
function makeItem(def) { return {instanceId:uid(),catalogId:def.id}; }
function uid() { return `${Date.now()}-${Math.random().toString(36).slice(2,8)}`; }
function getPlanet(id) { return PLANETS.find(p => p.id === id); }
function getDef(planetId,catalogId) { return CATALOGS[planetId].find(i => i.id === catalogId); }
function activeSave() { return saves.find(s => s.id === activeId); }
function saveAll() { localStorage.setItem(STORAGE,JSON.stringify(saves)); }
function esc(text) { return String(text).replace(/[&<>"]/g,c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"})[c]); }
function levelFor(stars) { return Math.floor(stars/50)+1; }
function xpInLevel(stars) { return stars%50; }
function mapSize(s) { const level=levelFor(s.stars); return level>=7?8:level>=4?7:6; }
function totalObjects(s) { return s.inventory.length+s.placements.length; }
function toast(message) { const el=document.querySelector("#toast"); el.textContent=message; el.classList.add("show"); clearTimeout(toastTimer); toastTimer=setTimeout(()=>el.classList.remove("show"),2500); }
function focusableIn(container){return [...container.querySelectorAll('button:not([disabled]),input:not([disabled]),[tabindex]:not([tabindex="-1"])')].filter(el=>!el.hidden)}
function trapDialogFocus(event,dialog){if(event.key==="Escape"){event.preventDefault();dialog.querySelector("[data-dialog-cancel]")?.click();return}if(event.key!=="Tab")return;const items=focusableIn(dialog);if(!items.length)return;const first=items[0],last=items[items.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}
function closeDialog(dialog,restore){dialog.remove();if(restore?.isConnected)restore.focus();else document.querySelector("#answerInput")?.focus()}
function bindDialog(dialog,restore){dialog.addEventListener("keydown",event=>trapDialogFocus(event,dialog));dialog.querySelector("[data-dialog-cancel]")?.addEventListener("click",()=>closeDialog(dialog,restore))}
function shell(content,showGallery=false) { return `<header class="topbar"><div class="brand"><span class="brand-mark">R</span>Rechenrakete</div><div class="top-actions">${showGallery?`<button class="ghost" id="galleryBtn">Meine Welten</button>`:""}<button class="ghost install-app" type="button" data-install-app>Installieren</button></div></header>${content}`; }

function planetMark(planetId,small=false) {
  const p=getPlanet(planetId);
  return `<svg class="planet-mark ${small?"small":""}" viewBox="0 0 120 100" aria-hidden="true"><ellipse cx="60" cy="83" rx="48" ry="10" fill="rgba(30,20,80,.16)"/><circle cx="60" cy="49" r="37" fill="${p.planet}"/><path d="M28 47c18 8 45-18 67-6M35 65c17-8 38 5 55-7" fill="none" stroke="rgba(255,255,255,.35)" stroke-width="8" stroke-linecap="round"/>${planetId==="luma"?`<path d="M58 60V36" stroke="#68493d" stroke-width="6"/><circle cx="58" cy="31" r="14" fill="#4f9c58"/>`:planetId==="coralia"?`<path d="M45 61c8-25 25 10 34-19M42 53c-10-9-12 4-8 13M73 52c13-10 16 4 8 14" fill="none" stroke="#fff0ad" stroke-width="6" stroke-linecap="round"/>`:`<rect x="41" y="31" width="38" height="33" rx="9" fill="#514298"/><circle cx="52" cy="46" r="4" fill="#aaf5ff"/><circle cx="68" cy="46" r="4" fill="#aaf5ff"/><path d="M53 56h14M60 31V23" stroke="#aaf5ff" stroke-width="4" stroke-linecap="round"/>`}</svg>`;
}

function renderHome() {
  activeId=null;
  const cards=PLANETS.map(p=>`<button class="planet-card" data-planet="${p.id}" style="--planet-bg:${p.bg};--planet:${p.planet};--button:${p.button}"><div class="planet-preview">${planetMark(p.id)}</div><div class="planet-info"><h2>${p.name}</h2><p>${p.tag}</p><span class="choose">Diesen Planeten entdecken <b>→</b></span></div></button>`).join("");
  app.innerHTML=shell(`<section class="hero"><h1>Rechne. Sammle.<br><span>Bau deine Welt!</span></h1><p>Jede richtige Rechnung bringt deine eigene Siedlung zum Wachsen.</p></section><section class="planet-grid">${cards}</section>`,saves.length>0);
  document.querySelectorAll("[data-planet]").forEach(b=>b.addEventListener("click",()=>createWorld(b.dataset.planet)));
  bindGallery();
}
function renderGallery() {
  activeId=null;
  const cards=saves.length?saves.map(s=>{const p=getPlanet(s.planetId);return `<article class="save-card"><div class="save-orb" style="--planet:${p.planet}">${planetMark(p.id,true)}</div><div class="save-details"><h2>${esc(s.name)}</h2><p>Level ${levelFor(s.stars)} · ${s.placements.length} gebaut · ${s.inventory.length} in der Baukiste</p></div><button class="play-small" data-open="${s.id}">Besuchen</button></article>`}).join(""):`<p class="gallery-empty">Noch keine Welt entdeckt.</p>`;
  app.innerHTML=shell(`<h1 class="section-title">Meine Welten</h1><section class="gallery">${cards}</section><button class="new-world" id="newWorld">+ Neue Welt entdecken</button>`,true);
  document.querySelectorAll("[data-open]").forEach(b=>b.addEventListener("click",()=>openWorld(b.dataset.open)));
  document.querySelector("#newWorld").addEventListener("click",renderHome); bindGallery();
}
function bindGallery(){document.querySelector("#galleryBtn")?.addEventListener("click",renderGallery)}
function createWorld(planetId){const p=getPlanet(planetId);const n=saves.filter(s=>s.planetId===planetId).length+1;const world={id:uid(),planetId,name:n===1?p.name:`${p.name} ${n}`,stars:0,streak:0,totalCorrect:0,day:0,population:0,tools:{wrench:0,can:0,hammer:0},activeEvent:null,nextEventDay:4,tutorialEnabled:null,tutorialStep:0,inventory:[],placements:[]};saves.push(world);saveAll();openWorld(world.id)}
function openWorld(id){activeId=id;currentQuestion=makeQuestion();selectedItemId=null;selectedPlacementId=null;renderGame();const s=activeSave();if(s?.tutorialEnabled===null)showTutorialChoice(s)}

function resources(s){return s.placements.reduce((sum,pl)=>{if(pl.damaged)return sum;const d=getDef(s.planetId,pl.catalogId);Object.entries(d?.produces||{}).forEach(([k,v])=>sum[k]+=v);return sum},{energy:0,food:0,homes:0})}
function settlementMetrics(s,nextPopulation=s.population){const supply=resources(s);const buildingEnergy=s.placements.filter(pl=>!pl.damaged).reduce((n,pl)=>n+(getDef(s.planetId,pl.catalogId)?.requires?.energy||0),0);return{supply,energyNeed:Math.ceil(nextPopulation/2)+buildingEnergy,foodNeed:Math.ceil(nextPopulation/2),homesNeed:nextPopulation}}
function isSupplied(s,nextPopulation=s.population){const m=settlementMetrics(s,nextPopulation);return m.supply.homes>=m.homesNeed&&m.supply.food>=m.foodNeed&&m.supply.energy>=m.energyNeed}
function resourceBar(s){const m=settlementMetrics(s);const chip=(kind,label,need,supply)=>`<span class="${supply>=need?"supplied":"shortage"}"><i class="res ${kind}">${kind==="energy"?"E":kind==="food"?"N":"W"}</i><b>${need}/${supply}</b> ${label}</span>`;return`<div class="resource-bar"><span class="population-chip"><i class="res population">P</i><b>${s.population}</b> Bewohner</span>${chip("energy","Energie",m.energyNeed,m.supply.energy)}${chip("food","Nahrung",m.foodNeed,m.supply.food)}${chip("homes","Wohnraum",m.homesNeed,m.supply.homes)}</div>`}
function toolBar(s){return`<div class="tool-bar"><span><i>🔧</i>${s.tools.wrench}</span><span><i>💧</i>${s.tools.can}</span><span><i>🔨</i>${s.tools.hammer}</span></div>`}
function guideArt(planetId){const p=getPlanet(planetId),c=p.palette;return`<svg viewBox="0 0 80 80" aria-hidden="true"><circle cx="40" cy="42" r="29" fill="${c.main}"/><path d="M24 31c7-15 27-18 36 0" fill="${c.light}"/><circle cx="31" cy="42" r="5" fill="${c.glass}"/><circle cx="50" cy="42" r="5" fill="${c.glass}"/><circle cx="31" cy="42" r="2" fill="${c.dark}"/><circle cx="50" cy="42" r="2" fill="${c.dark}"/><path d="M32 54q8 7 16 0" fill="none" stroke="${c.dark}" stroke-width="4" stroke-linecap="round"/><path d="M40 13V6" stroke="${c.dark}" stroke-width="4"/><circle cx="40" cy="5" r="4" fill="${c.accent}"/></svg>`}
function currentObjective(s){const p=getPlanet(s.planetId),m=settlementMetrics(s),next=settlementMetrics(s,s.population+1);if(s.activeEvent){const e=s.activeEvent;if(e.toolReady)return`${e.title}: Das Werkzeug ist fertig. Repariere das markierte Gebäude.`;return`${e.title}: Noch ${Math.max(0,e.target-e.progress)} richtige Aufgaben bis zum Werkzeug.`}if(!s.placements.some(pl=>getDef(s.planetId,pl.catalogId)?.kind==="home"))return"Baue zuerst ein Zuhause für deine neuen Bewohner.";if(m.supply.energy<m.energyNeed||m.supply.food<m.foodNeed)return"Die Versorgung braucht Hilfe. Baue Energie und Nahrung aus.";if(s.population===0&&next.supply.energy<next.energyNeed)return"Für den ersten Bewohner fehlt Energie. Der nächste Bauplan hilft dir.";if(s.population===0&&next.supply.food<next.foodNeed)return"Für den ersten Bewohner fehlt Nahrung. Der nächste Bauplan hilft dir.";if(s.population<3)return"Kapitel 1: Begrüße 3 Bewohner auf deinem Planeten.";if(s.population<6)return"Kapitel 2: Versorge eine Siedlung mit 6 Bewohnern.";if(!s.placements.some(pl=>getDef(s.planetId,pl.catalogId)?.kind==="landmark"))return`Finale: Baue das Wahrzeichen von ${p.name}.`;return"Deine Siedlung blüht! Entdecke weitere seltene Baupläne."}
function guideCard(s){const p=getPlanet(s.planetId);return`<div class="guide-card"><span class="guide-avatar">${guideArt(p.id)}</span><div><b>${p.guide} sagt:</b><p>${currentObjective(s)}</p></div></div>`}

function renderGame(){
  const s=activeSave();if(!s)return renderGallery();const p=getPlanet(s.planetId);const level=levelFor(s.stars),xp=xpInLevel(s.stars);
  const mission=s.activeEvent?`<div class="mission-banner ${s.activeEvent.toolReady?"ready":""}"><b>${s.activeEvent.toolReady?"Werkzeug bereit!":s.activeEvent.title}</b><span>${s.activeEvent.toolReady?"Öffne die Siedlung und repariere das Gebäude.":`${s.activeEvent.progress}/${s.activeEvent.target} Reparatur-Aufgaben`}</span></div>`:"";
  const buildReady=s.inventory.length>0;
  const settlement=`<aside class="settlement-summary" style="--world-sky:${p.sky};--world-ground:${p.ground}"><div class="summary-art">${planetMark(p.id)}<div><span>${s.population}</span> ${s.population===1?"Bewohner lebt":"Bewohner leben"} hier</div></div>${guideCard(s)}<div class="build-callout"><h2>${buildReady?"Ein Bauplan wartet":"Deine Siedlung ruht"}</h2><p>${buildReady?"Ich zeige dir, wo dein neuer Bauplan gut passt.":s.placements.length?"Rechne weiter, wenn du deiner Welt etwas Neues schenken möchtest.":"Nach drei richtigen Aufgaben wartet dein erster Bauplan."}</p><button class="primary" id="buildBtn">${buildReady?"Bauplan platzieren":"Siedlung ansehen"}</button></div></aside>`;
  const quiz=`<section class="quiz-panel math-focus">${mission}<div class="streak">${s.streak>=3?"Super-Serie!":"Noch "+(3-s.totalCorrect%3)+" Rechnungen bis zum nächsten Bauplan"}</div><p class="mission">Nimm dir Zeit. Löse eine Rechnung nach der anderen.</p><h2 class="question">${currentQuestion.a} ${currentQuestion.op} ${currentQuestion.b}</h2><p class="hint" id="feedback" role="status" aria-live="polite">${hintFor(currentQuestion,level)}</p><div class="answer-row"><input id="answerInput" class="answer-input" inputmode="none" readonly aria-readonly="true" autocomplete="off" aria-label="Deine Antwort – nutze die Zahlentasten der App" aria-describedby="feedback" placeholder="?"/><button id="answerBtn" class="answer-btn" aria-label="Antwort prüfen">✓</button></div><div class="number-pad" aria-label="Zahlentastatur">${[1,2,3,4,5,6,7,8,9,"⌫",0,"C"].map(n=>`<button data-key="${n}" class="${n==="⌫"||n==="C"?"erase":""}" aria-label="${n==="⌫"?"Letzte Ziffer löschen":n==="C"?"Antwort löschen":n}">${n}</button>`).join("")}</div><p class="quick-tip">Die App-Tastatur bleibt offen – so hast du die Rechnung immer im Blick.</p></section>`;
  app.innerHTML=shell(`<section class="game-header"><div><button class="back" id="backBtn">← Zurück zu meinen Welten</button><h1 class="world-name">${esc(s.name)}</h1><p class="world-sub">${p.tag} · Planetentag ${s.day}</p></div><div class="stats"><div class="stat"><b>★ ${s.stars}</b><small>Sterne</small></div></div><div class="progress-wrap"><span>Level ${level}</span><div class="progress"><i style="transform:scaleX(${xp/50})"></i></div><span>${xp}/50</span></div></section><section class="play-layout">${quiz}${settlement}</section>`,true);
  bindGallery();document.querySelector("#backBtn").addEventListener("click",renderGallery);document.querySelector("#buildBtn").addEventListener("click",renderBuild);
  const input=document.querySelector("#answerInput");const enterKey=key=>{if(key==="C")input.value="";else if(key==="⌫"||key==="Backspace")input.value=input.value.slice(0,-1);else if(/^\d$/.test(key)&&input.value.length<3)input.value+=key};input.focus();document.querySelector("#answerBtn").addEventListener("click",checkAnswer);input.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();checkAnswer();return}if(/^\d$/.test(e.key)||e.key==="Backspace"||e.key==="Delete"){e.preventDefault();enterKey(e.key==="Delete"?"C":e.key)}});document.querySelectorAll("[data-key]").forEach(btn=>btn.addEventListener("click",()=>{enterKey(btn.dataset.key);input.focus()}));
}
function makeQuestion(){const s=activeSave();const l=levelFor(s.stars);const max=l<=2?20:l<=4?50:100;const op=Math.random()<.52?"+":"−";let a,b;if(op==="+"){a=1+Math.floor(Math.random()*(max-1));b=1+Math.floor(Math.random()*(max-a))}else{a=5+Math.floor(Math.random()*(max-4));b=1+Math.floor(Math.random()*a)}return{a,b,op,answer:op==="+"?a+b:a-b}}
function hintFor(q,level){if(level<=2)return q.op==="+"?"Tipp: Zähle in kleinen Schritten weiter.":"Tipp: Zähle rückwärts.";return q.op==="+"?"Tipp: Rechne zuerst bis zum nächsten Zehner.":"Tipp: Zerlege die Zahl in Zehner und Einer."}
function checkAnswer(){const input=document.querySelector("#answerInput"),feedback=document.querySelector("#feedback");if(input.value==="")return;const s=activeSave();if(Number(input.value)!==currentQuestion.answer){s.streak=0;saveAll();feedback.textContent="Fast! Versuch es noch einmal. Du kannst das!";feedback.classList.add("wrong");input.value="";input.focus();return}s.streak++;s.totalCorrect++;const bonus=s.streak>=5?3:s.streak>=3?2:1;const earned=5*bonus;s.stars+=earned;progressMission(s);saveAll();if(s.totalCorrect%3===0)advanceDay(s,earned);else{toast(`Richtig! +${earned} Sterne`);currentQuestion=makeQuestion();renderGame()}}
function nextReward(s){const catalog=CATALOGS[s.planetId];const owned=[...s.inventory,...s.placements];const ownedCount=owned.length;if(ownedCount<4)return catalog[ownedCount];const landmark=catalog.find(d=>d.kind==="landmark");if(s.population>=6&&landmark&&!owned.some(i=>i.catalogId===landmark.id))return landmark;const m=settlementMetrics(s);if(m.supply.homes<=s.population)return catalog.find(d=>d.kind==="home");if(m.supply.energy<m.energyNeed+1)return catalog.find(d=>["solar","tide","wind"].includes(d.kind));if(m.supply.food<m.foodNeed+1)return catalog.find(d=>d.kind==="garden");const rarePool=catalog.slice(4).filter(d=>d.kind!=="landmark");const notOwned=rarePool.filter(d=>!owned.some(i=>i.catalogId===d.id));if(notOwned.length)return notOwned[Math.floor(Math.random()*notOwned.length)];const repeatable=catalog.filter(d=>["home","path","tree","garden","solar","tide"].includes(d.kind));return repeatable[Math.floor(Math.random()*repeatable.length)]}
function progressMission(s){const e=s.activeEvent;if(!e||e.toolReady)return;e.progress++;if(e.progress>=e.target){s.tools[e.tool]++;e.toolReady=true;toast("Werkzeug verdient! Öffne deine Siedlung.")}}
function growPopulation(s){const next=s.population+1;if(resources(s).homes<=s.population)return null;if(isSupplied(s,next)){s.population=next;return`Ein neuer Bewohner ist eingezogen. Jetzt leben ${s.population} Bewohner hier!`}const m=settlementMetrics(s,next);if(m.supply.energy<m.energyNeed)return"Ein neuer Bewohner wartet noch: Die Siedlung braucht mehr Energie.";if(m.supply.food<m.foodNeed)return"Ein neuer Bewohner wartet noch: Die Siedlung braucht mehr Nahrung.";return"Ein neuer Bewohner wartet noch auf ein freies Zuhause."}
function damageCandidate(s){const candidates=s.placements.filter(pl=>!pl.damaged&&Object.keys(getDef(s.planetId,pl.catalogId)?.produces||{}).some(k=>["energy","food","homes"].includes(k)));if(!candidates.length)return null;return candidates[Math.floor(Math.random()*candidates.length)]}
function eventCopy(planetId,resource){const copy={luma:{energy:["Großer Waldwind","Starke Böen haben eine Energieanlage beschädigt."],food:["Freche Funkelfalter","Die Falter haben eine Nahrungsanlage durcheinandergebracht."],homes:["Knarrender Ast","Ein Zuhause braucht nach dem Sturm eine Reparatur."]},coralia:{energy:["Weltraumsturm über der Lagune","Eine gewaltige Welle hat eine Energieanlage beschädigt."],food:["Wirbel in der Bucht","Die Strömung hat eine Nahrungsanlage erwischt."],homes:["Hohe Flut","Ein Zuhause wurde von der Flut beschädigt."]},zapp:{energy:["Ionensturm","Ein Energiestoß hat eine Anlage lahmgelegt."],food:["Hydro-Fehler","Eine Nahrungsanlage meldet einen Defekt."],homes:["Kleiner Meteorit","Ein Wohnmodul braucht eine Reparatur."]}};return copy[planetId][resource]}
function triggerEvent(s){const pl=damageCandidate(s);if(!pl)return null;const def=getDef(s.planetId,pl.catalogId);const resource=def.produces.energy?"energy":def.produces.food?"food":"homes";const tool=resource==="energy"?"wrench":resource==="food"?"can":"hammer";const [title,text]=eventCopy(s.planetId,resource);const before=resources(s)[resource];pl.damaged=true;s.activeEvent={id:uid(),placementId:pl.instanceId,resource,requiredMin:before,tool,title,text,target:2,progress:0,toolReady:false};s.nextEventDay=s.day+3+Math.floor(Math.random()*3);return`${text} Löse 2 Aufgaben für das passende Werkzeug oder baue eine zweite Versorgung.`}
function tutorialStory(s){if(!s.tutorialEnabled||s.day>4)return null;const p=getPlanet(s.planetId);const stories=["",`Willkommen! Baue dein erstes Zuhause. Dann können Bewohner auf ${p.name} einziehen.`,`Heute braucht die Siedlung Energie. Platziere die neue Energiequelle.`,`Jetzt fehlt noch Nahrung. Baue die neue Nahrungsanlage.`,`Gut vorbereitet! Ab jetzt können kleine Ereignisse und Reparaturmissionen auftreten.`];s.tutorialStep=s.day;return stories[s.day]}
function advanceDay(s,earned){s.day++;const def=nextReward(s),item=makeItem(def);s.inventory.push(item);const growth=growPopulation(s);let story=tutorialStory(s);if(!s.activeEvent&&s.day>=s.nextEventDay){const eventStory=triggerEvent(s);if(eventStory)story=eventStory}story||=growth||`Planetentag ${s.day} beginnt. Deine Siedlung ist gut versorgt.`;saveAll();showDayReport(s,earned,item,story)}
function showDayReport(s,earned,item,story){const def=getDef(s.planetId,item.catalogId),p=getPlanet(s.planetId);renderGame();const restore=document.querySelector("#answerInput");app.insertAdjacentHTML("beforeend",`<div class="reward-modal" id="reward" role="dialog" aria-modal="true" aria-labelledby="dayReportTitle" aria-describedby="dayReportStory"><div class="reward-card day-report"><div class="report-guide">${guideArt(p.id)}</div><span class="rarity">PLANETENTAG ${s.day}</span><h2 id="dayReportTitle">${p.guide} berichtet</h2><p class="story-text" id="dayReportStory">${story}</p><div class="blueprint-reward"><span>${objectSvg(def,p.palette,"preview")}</span><div><small>NEUER BAUPLAN</small><b>${def.name}</b><em>+${earned} Sterne</em></div></div><div class="reward-actions"><button class="secondary" id="keepPlaying" data-dialog-cancel>Später weiterrechnen</button><button class="primary" id="buildNow">Bauplan platzieren</button></div></div></div>`);const dialog=document.querySelector("#reward");bindDialog(dialog,restore);dialog.querySelector("#keepPlaying").addEventListener("click",()=>{currentQuestion=makeQuestion();renderGame();document.querySelector("#answerInput")?.focus()});dialog.querySelector("#buildNow").addEventListener("click",()=>{currentQuestion=makeQuestion();selectedItemId=item.instanceId;renderBuild()});dialog.querySelector("#buildNow").focus()}
function showTutorialChoice(s){const p=getPlanet(s.planetId),restore=document.querySelector("#answerInput");app.insertAdjacentHTML("beforeend",`<div class="reward-modal" id="tutorialChoice" role="dialog" aria-modal="true" aria-labelledby="tutorialTitle" aria-describedby="tutorialText"><div class="reward-card tutorial-choice"><div class="report-guide">${guideArt(p.id)}</div><h2 id="tutorialTitle">Willkommen auf ${p.name}!</h2><p id="tutorialText">${p.guide} zeigt dir immer nur den nächsten kleinen Schritt.</p><div class="choice-stack"><button class="primary" id="withTutorial">Zeig mir den ersten Schritt</button><button class="secondary" id="skipTutorial" data-dialog-cancel>Ohne Begleitung starten</button></div></div></div>`);const dialog=document.querySelector("#tutorialChoice");bindDialog(dialog,restore);dialog.querySelector("#withTutorial").addEventListener("click",()=>{s.tutorialEnabled=true;saveAll();renderGame();toast(`${p.guide} begleitet dich!`)});dialog.querySelector("#skipTutorial").addEventListener("click",()=>{s.tutorialEnabled=false;s.tutorialStep=4;saveAll();renderGame();toast("Freier Siedlungsmodus gestartet.")});dialog.querySelector("#withTutorial").focus()}

function terrainAt(planetId,x,y,size){if(planetId==="coralia")return(x===0||y===size-1||x+y>=size+2)?"water":"land";return"land"}
function tileColor(p,terrain,x,y){if(terrain==="water")return x%2===y%2?"#199fbd":"#138ead";if(p.id==="coralia")return(x+y)%2?"#f0c36c":"#e4ad53";if(p.id==="luma")return(x+y)%2?"#65b85f":"#79c96b";return(x+y)%2?"#6f6796":"#8178a8"}
function terrainLegend(p){if(p.id==="coralia")return`<span class="terrain-legend"><i class="land-swatch"></i>Land <i class="water-swatch"></i>Wasser</span>`;if(p.id==="luma")return`<span class="terrain-legend single"><i class="forest-swatch"></i>Waldgrund</span>`;return`<span class="terrain-legend single"><i class="space-swatch"></i>Mondgestein</span>`}
function terrainTexture(planetId,terrain,px,py,x,y){if(terrain==="water")return`<g class="terrain-texture water-texture"><path d="M${px-23} ${py-6}q7-6 14 0t14 0t14 0M${px-17} ${py+7}q6-5 12 0t12 0"/></g>`;if(planetId==="luma")return`<g class="terrain-texture forest-texture"><path d="M${px-19} ${py+8}l3-9 3 9m18 3 2-8 3 7m12-8 2-6 2 6"/><circle cx="${px+15}" cy="${py-5}" r="2.4" class="forest-flower"/>${(x+y)%3===0?`<circle cx="${px-6}" cy="${py+4}" r="1.8" class="forest-dot"/>`:""}</g>`;if(planetId==="zapp")return`<g class="terrain-texture space-texture"><ellipse cx="${px-16}" cy="${py+4}" rx="6" ry="3"/><ellipse cx="${px+19}" cy="${py-4}" rx="3.5" ry="2"/><path d="M${px-4} ${py+9}v-7h9l4-5"/>${(x+y)%3===0?`<circle cx="${px+3}" cy="${py-7}" r="2"/>`:""}</g>`;return`<g class="terrain-texture land-texture"><circle cx="${px-17}" cy="${py+3}" r="2"/><circle cx="${px+18}" cy="${py-4}" r="2"/><path d="M${px-3} ${py+8}l3-7 3 7"/></g>`}
function canUseTerrain(def,terrain){return def.terrain==="any"||def.terrain===terrain}
function requirementsMet(def,s){const r=resources(s);return Object.entries(def.requires||{}).every(([key,value])=>r[key]>=value)}
function requirementText(def){const names={energy:"Energie",food:"Nahrung",homes:"Wohnraum"};const entries=Object.entries(def.requires||{});return entries.length?`Braucht ${entries.map(([k,v])=>`${v} ${names[k]}`).join(" und ")}`:"Kann sofort gebaut werden"}
function productionText(def){const names={energy:"Energie",food:"Nahrung",homes:"Wohnraum"};const entries=Object.entries(def.produces||{});return entries.length?`Gibt ${entries.map(([k,v])=>`+${v} ${names[k]}`).join(" und ")}`:"Dekoration und Verbindung"}

function renderBuild(){
  const s=activeSave();if(!s)return;if(!selectedItemId&&!selectedPlacementId&&s.inventory.length===1)selectedItemId=s.inventory[0].instanceId;const p=getPlanet(s.planetId);const selectedItem=s.inventory.find(i=>i.instanceId===selectedItemId);const selectedDef=selectedItem&&getDef(s.planetId,selectedItem.catalogId);const selectedPlacement=s.placements.find(i=>i.instanceId===selectedPlacementId);const selectedPlacedDef=selectedPlacement&&getDef(s.planetId,selectedPlacement.catalogId);
  app.innerHTML=shell(`<section class="builder-header"><div><button class="back" id="quizBtn">← Zurück zum Rechnen</button><h1>${esc(s.name)} bauen</h1><p>Planetentag ${s.day} · ${s.population} Bewohner</p></div>${resourceBar(s)}</section><section class="builder-layout"><aside class="build-panel">${guideCard(s)}<div class="inventory-head"><div><h2>Baukiste</h2><p>${s.inventory.length} Baupläne</p></div><span class="crate-icon">▦</span></div>${toolBar(s)}<div class="inventory">${renderInventory(s)}</div>${renderSelectionPanel(s,selectedDef,selectedPlacedDef,selectedPlacement)}</aside><div class="map-card"><div class="map-toolbar"><span><b>${mapSize(s)} × ${mapSize(s)}</b> Baufläche</span>${terrainLegend(p)}<span>${s.placements.length} gebaut</span></div><div class="board-wrap planet-${p.id}">${renderBoard(s,selectedDef)}</div><p class="map-hint" id="mapHint" role="status" aria-live="polite">${selectedDef?`${selectedDef.name} ist ausgewählt. Tippe auf ein leuchtendes Feld.`:selectedPlacedDef?selectedPlacement.damaged?`${selectedPlacedDef.name} ist beschädigt und braucht Hilfe.`:`${selectedPlacedDef.name} auswählen oder einpacken.`:"Wähle einen Bauplan. Danach zeigen leuchtende Felder, wo er passt."}</p></div></section>`,true);
  bindGallery();document.querySelector("#quizBtn").addEventListener("click",()=>{selectedItemId=null;selectedPlacementId=null;currentQuestion||=makeQuestion();renderGame()});bindBuilder(s);
}
function renderInventory(s){if(!s.inventory.length)return`<div class="empty-crate"><span>✓</span><b>${s.placements.length?"Alles verbaut!":"Noch ist sie leer"}</b><p>${s.placements.length?"Löse weitere Aufgaben für neue Baupläne.":"Nach 3 Aufgaben wartet hier dein erster Bauplan."}</p></div>`;return s.inventory.map(item=>{const d=getDef(s.planetId,item.catalogId);return`<button class="inventory-item ${item.instanceId===selectedItemId?"selected":""}" data-item="${item.instanceId}" draggable="true"><span class="item-art">${objectSvg(d,getPlanet(s.planetId).palette,"preview")}</span><span><b>${d.name}</b><small>${productionText(d)}</small></span></button>`}).join("")}
function toolName(tool){return{wrench:"Schraubenschlüssel",can:"Gießkanne",hammer:"Bauhammer"}[tool]}
function renderSelectionPanel(s,def,placedDef,placement){if(def)return`<div class="selection-card"><h3>${def.name}</h3><p>${def.text}</p><div class="info-pills"><span>${requirementText(def)}</span><span>${productionText(def)}</span></div>${requirementsMet(def,s)?`<p class="place-next">Als Nächstes: Tippe auf ein leuchtendes Feld auf der Karte.</p>`:`<p class="need-warning">Dir fehlt noch etwas. ${currentObjective(s)}</p>`}<button class="secondary full" id="cancelSelect">Anderen Bauplan wählen</button></div>`;if(placedDef&&placement?.damaged){const event=s.activeEvent?.placementId===placement.instanceId?s.activeEvent:null;const tool=event?.tool||(placedDef.produces?.energy?"wrench":placedDef.produces?.food?"can":"hammer");const ready=s.tools[tool]>0;return`<div class="selection-card damaged-card"><span class="damage-label">AUSSER BETRIEB</span><h3>${placedDef.name}</h3><p>${event?.text||"Dieses Gebäude muss repariert werden."}</p><div class="info-pills"><span>Braucht: ${toolName(tool)}</span><span>Liefert gerade keine Ressourcen</span></div><button class="primary full" id="repairObject" ${ready?"":"disabled"}>${ready?"Jetzt reparieren":event?`Noch ${Math.max(0,event.target-event.progress)} Aufgaben lösen`:"Werkzeug fehlt"}</button></div>`}if(placedDef)return`<div class="selection-card"><h3>${placedDef.name}</h3><p>${placedDef.text}</p><div class="object-actions"><button class="secondary" id="moveObject">Verschieben</button><button class="secondary danger" id="packObject">Einpacken</button></div></div>`;return`<div class="selection-card subtle"><h3>So wird gebaut</h3><p>Wähle einen Bauplan. Leuchtende Felder zeigen dir den passenden Platz. Fertig.</p></div>`}
function bindBuilder(s){
  document.querySelectorAll("[data-item]").forEach(b=>{b.addEventListener("click",()=>{selectedItemId=b.dataset.item;selectedPlacementId=null;renderBuild()});b.addEventListener("dragstart",e=>{selectedItemId=b.dataset.item;e.dataTransfer.setData("text/plain",b.dataset.item)})});
  document.querySelectorAll("[data-tile]").forEach(tile=>{const place=()=>placeSelected(s,Number(tile.dataset.x),Number(tile.dataset.y));tile.addEventListener("click",place);tile.addEventListener("keydown",event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();place()}else moveMapFocus(event,tile)});tile.addEventListener("dragover",e=>e.preventDefault());tile.addEventListener("drop",e=>{e.preventDefault();selectedItemId=e.dataTransfer.getData("text/plain");place()})});
  document.querySelectorAll("[data-placement]").forEach(node=>node.addEventListener("click",e=>{e.stopPropagation();selectedPlacementId=node.dataset.placement;selectedItemId=null;renderBuild()}));
  document.querySelector("#cancelSelect")?.addEventListener("click",()=>{selectedItemId=null;renderBuild()});document.querySelector("#moveObject")?.addEventListener("click",()=>packSelected(s,true));document.querySelector("#packObject")?.addEventListener("click",()=>packSelected(s,false));document.querySelector("#repairObject")?.addEventListener("click",()=>repairSelected(s));
}
function moveMapFocus(event,node){const direction={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[event.key];if(!direction)return;const x=Number(node.dataset.x),y=Number(node.dataset.y);if(!Number.isFinite(x)||!Number.isFinite(y))return;const board=node.closest("svg"),next=board?.querySelector(`[data-tile][data-x="${x+direction[0]}"][data-y="${y+direction[1]}"]`);if(next){event.preventDefault();board.querySelector("[data-tile][tabindex=\"0\"]")?.setAttribute("tabindex","-1");next.setAttribute("tabindex","0");next.focus()}}
function placeSelected(s,x,y){if(!selectedItemId){const found=s.placements.find(p=>p.x===x&&p.y===y);if(found){selectedPlacementId=found.instanceId;renderBuild()}return}const item=s.inventory.find(i=>i.instanceId===selectedItemId);if(!item)return;const def=getDef(s.planetId,item.catalogId);const terrain=terrainAt(s.planetId,x,y,mapSize(s));if(s.placements.some(p=>p.x===x&&p.y===y)){toast("Dieses Feld ist schon belegt.");return}if(!canUseTerrain(def,terrain)){toast(def.terrain==="water"?"Das gehört ins Wasser.":"Das braucht festen Boden.");return}if(!requirementsMet(def,s)){toast(requirementText(def));return}s.inventory=s.inventory.filter(i=>i.instanceId!==item.instanceId);s.placements.push({...item,x,y});selectedItemId=null;const rescued=maybeResolveByBackup(s);saveAll();renderBuild();toast(rescued?"Die Ersatzversorgung hat die Krise gelöst!":`${def.name} wurde gebaut!`)}
function packSelected(s,move){const pl=s.placements.find(p=>p.instanceId===selectedPlacementId);if(!pl)return;s.placements=s.placements.filter(p=>p.instanceId!==pl.instanceId);s.inventory.push({instanceId:pl.instanceId,catalogId:pl.catalogId});selectedPlacementId=null;selectedItemId=move?pl.instanceId:null;saveAll();renderBuild();toast(move?"Wähle jetzt einen neuen Platz.":"Zurück in der Baukiste.")}
function maybeResolveByBackup(s){const e=s.activeEvent;if(!e)return false;if(resources(s)[e.resource]<e.requiredMin)return false;const broken=s.placements.find(pl=>pl.instanceId===e.placementId);if(broken)broken.damaged=false;s.activeEvent=null;s.stars+=5;return true}
function repairSelected(s){const pl=s.placements.find(p=>p.instanceId===selectedPlacementId);if(!pl?.damaged)return;const def=getDef(s.planetId,pl.catalogId);const event=s.activeEvent?.placementId===pl.instanceId?s.activeEvent:null;const tool=event?.tool||(def.produces?.energy?"wrench":def.produces?.food?"can":"hammer");if(s.tools[tool]<1){toast(`${toolName(tool)} fehlt noch.`);return}s.tools[tool]--;pl.damaged=false;if(event)s.activeEvent=null;s.stars+=5;selectedPlacementId=null;saveAll();renderBuild();toast(`${def.name} repariert! +5 Sterne`)}

function renderResidents(s,size,cx,startY,dx,dy){const p=getPlanet(s.planetId),spots=[];for(let y=size-1;y>=0;y--)for(let x=0;x<size;x++)if(terrainAt(s.planetId,x,y,size)==="land"&&!s.placements.some(pl=>pl.x===x&&pl.y===y))spots.push({x,y});return spots.slice(0,Math.min(s.population,8)).map((spot,i)=>{const px=cx+(spot.x-spot.y)*dx+(i%2?9:-7),py=startY+(spot.x+spot.y)*dy-21;return`<g class="resident" transform="translate(${px} ${py})"><title>Bewohner ${i+1}</title><ellipse cx="0" cy="19" rx="10" ry="4" fill="rgba(39,35,84,.2)"/><circle cx="0" cy="2" r="7" fill="${p.palette.light}" stroke="${p.palette.dark}" stroke-width="2"/><path d="M-7 12q7-8 14 0v9H-7Z" fill="${p.palette.accent}" stroke="${p.palette.dark}" stroke-width="2"/><circle cx="-2.5" cy="1" r="1.3" fill="${p.palette.dark}"/><circle cx="2.5" cy="1" r="1.3" fill="${p.palette.dark}"/></g>`}).join("")}
function renderBoard(s,selectedDef){const p=getPlanet(s.planetId),size=mapSize(s),cx=350,startY=58,dx=42,dy=24;let tiles="",objects="";for(let sum=0;sum<=2*(size-1);sum++){for(let x=0;x<size;x++){const y=sum-x;if(y<0||y>=size)continue;const px=cx+(x-y)*dx,py=startY+(x+y)*dy,terrain=terrainAt(s.planetId,x,y,size),pl=s.placements.find(o=>o.x===x&&o.y===y),occupied=Boolean(pl),valid=selectedDef&&!occupied&&canUseTerrain(selectedDef,terrain)&&requirementsMet(selectedDef,s),placedDef=pl&&getDef(s.planetId,pl.catalogId),tileState=occupied?`${placedDef.name}${pl.damaged?", außer Betrieb":""}: auswählen`:valid?"passend für den ausgewählten Bauplan":"frei";tiles+=`<polygon class="map-tile ${terrain} ${valid?"valid":""} ${occupied?"occupied":""}" data-tile="1" data-x="${x}" data-y="${y}" role="button" tabindex="${x===0&&y===0?0:-1}" aria-label="Baufeld ${x+1}, ${y+1}: ${tileState}" aria-describedby="mapHint" points="${px},${py-dy} ${px+dx},${py} ${px},${py+dy} ${px-dx},${py}" fill="${tileColor(p,terrain,x,y)}"/>${terrainTexture(p.id,terrain,px,py,x,y)}`;if(pl){objects+=`<g class="map-object ${pl.damaged?"damaged-object":""} ${pl.instanceId===selectedPlacementId?"selected-object":""}" data-placement="${pl.instanceId}" aria-hidden="true" transform="translate(${px-48} ${py-85})"><title>${placedDef.name}${pl.damaged?" – außer Betrieb":""}</title>${objectSvg(placedDef,p.palette,"board")}${pl.damaged?`<g class="damage-marker"><circle cx="78" cy="18" r="13"/><path d="m72 12 12 12m0-12L72 24"/></g>`:""}</g>`}}}return`<svg class="iso-board planet-${p.id}" viewBox="0 0 700 445" role="group" aria-label="Baukarte von ${esc(s.name)}. Mit Tab erreichst du die Karte; Pfeiltasten wechseln Felder, Eingabe wählt oder baut."><defs><filter id="softShadow" x="-30%" y="-30%" width="160%" height="180%"><feDropShadow dx="0" dy="5" stdDeviation="4" flood-color="#2f275d" flood-opacity=".25"/></filter></defs><ellipse cx="350" cy="${startY+(size-1)*2*dy+25}" rx="${size*dx*.84}" ry="52" fill="rgba(39,35,84,.13)"/>${tiles}${objects}${renderResidents(s,size,cx,startY,dx,dy)}</svg>`}

function objectSvg(def,c,mode){const content=artFor(def.kind,c);if(mode==="board")return`<svg width="96" height="96" viewBox="0 0 100 100" overflow="visible">${content}</svg>`;return`<svg viewBox="0 0 100 100" aria-hidden="true">${content}</svg>`}
function artFor(kind,c){
  const shadow=`<ellipse cx="50" cy="84" rx="32" ry="8" fill="rgba(32,29,73,.18)"/>`;
  if(kind==="home")return`${shadow}<g filter="url(#softShadow)"><path d="M23 48 50 28l28 20v31H23Z" fill="${c.main}"/><path d="m17 49 33-27 34 27-8 8-26-21-26 21Z" fill="${c.dark}"/><path d="M43 60h15v19H43Z" fill="${c.dark}"/><rect x="27" y="55" width="11" height="11" rx="2" fill="${c.glass}"/><rect x="62" y="55" width="11" height="11" rx="2" fill="${c.glass}"/><circle cx="55" cy="69" r="2" fill="${c.light}"/></g>`;
  if(kind==="solar")return`${shadow}<g filter="url(#softShadow)"><path d="M24 69h52l-8 13H31Z" fill="${c.dark}"/><path d="M25 39h54L70 70H18Z" fill="#3d579e" stroke="${c.light}" stroke-width="3"/><path d="M43 40 37 69M62 40l-6 29M22 54h52" stroke="${c.glass}" stroke-width="2"/><path d="M48 70v10M61 70v10" stroke="${c.dark}" stroke-width="5"/></g>`;
  if(kind==="garden")return`${shadow}<g filter="url(#softShadow)"><path d="m17 61 42-24 27 16-42 25Z" fill="#7a513d" stroke="${c.light}" stroke-width="3"/><path d="m29 61 34-19M41 69l34-20" stroke="#b98957" stroke-width="5"/>${[[36,53],[50,56],[62,48],[49,66]].map(([x,y])=>`<path d="M${x} ${y}v-10" stroke="#3e914f" stroke-width="3"/><circle cx="${x-3}" cy="${y-9}" r="4" fill="${c.accent}"/><circle cx="${x+3}" cy="${y-12}" r="4" fill="${c.light}"/>`).join("")}</g>`;
  if(kind==="path")return`${shadow}<path d="m13 67 44-27 31 18-45 27Z" fill="${c.light}" stroke="${c.dark}" stroke-width="3"/><path d="m31 68 33-20M45 78l33-20" stroke="${c.main}" stroke-width="5" stroke-linecap="round"/>`;
  if(kind==="wind")return`${shadow}<g filter="url(#softShadow)"><path d="M47 43h7l7 39H40Z" fill="${c.light}" stroke="${c.dark}" stroke-width="3"/><circle cx="50" cy="39" r="6" fill="${c.main}"/><path d="M50 34 34 14c-9 7-4 19 16 25M55 40l25-8c-1-12-16-13-30 7M48 44 38 68c10 6 20-4 12-29" fill="${c.glass}" stroke="${c.dark}" stroke-width="3"/></g>`;
  if(kind==="tide")return`${shadow}<g filter="url(#softShadow)"><path d="M26 67h48l-7 13H32Z" fill="${c.dark}"/><circle cx="50" cy="48" r="22" fill="${c.glass}" stroke="${c.dark}" stroke-width="5"/><circle cx="50" cy="48" r="7" fill="${c.main}"/>${[0,60,120,180,240,300].map(a=>`<path d="M50 48v-17" stroke="${c.main}" stroke-width="7" transform="rotate(${a} 50 48)"/>`).join("")}</g>`;
  if(kind==="greenhouse")return`${shadow}<g filter="url(#softShadow)"><path d="M18 56 49 32l34 20-32 25Z" fill="${c.accent}"/><path d="M20 55c5-31 48-34 61-3L50 70Z" fill="${c.glass}" fill-opacity=".82" stroke="${c.light}" stroke-width="4"/><path d="M50 35v35M28 47l43 16" stroke="rgba(255,255,255,.75)" stroke-width="3"/><circle cx="48" cy="58" r="7" fill="#56af5d"/></g>`;
  if(kind==="workshop")return`${shadow}<g filter="url(#softShadow)"><path d="M20 48 49 31l31 18v31H20Z" fill="${c.main}"/><path d="m16 49 33-22 35 21-7 9-28-17-27 17Z" fill="${c.dark}"/><rect x="31" y="58" width="38" height="22" rx="3" fill="${c.light}"/><circle cx="50" cy="55" r="12" fill="${c.glass}" stroke="${c.dark}" stroke-width="4"/><path d="M50 46v18M41 55h18" stroke="${c.dark}" stroke-width="4"/></g>`;
  if(kind==="landmark")return`${shadow}<g filter="url(#softShadow)"><path d="m18 70 32-46 32 46-9 12H27Z" fill="${c.main}" stroke="${c.dark}" stroke-width="4"/><path d="m50 24 9 31-9 18-9-18Z" fill="${c.glass}"/><circle cx="50" cy="20" r="10" fill="${c.light}" stroke="${c.dark}" stroke-width="3"/><path d="M27 70h46M33 58h34" stroke="${c.dark}" stroke-width="4"/></g>`;
  if(kind==="tower")return`${shadow}<g filter="url(#softShadow)"><path d="M37 31h27l8 51H28Z" fill="${c.light}" stroke="${c.dark}" stroke-width="3"/><path d="M32 24h37v17H32Z" fill="${c.main}" stroke="${c.dark}" stroke-width="3"/><path d="M39 24c1-18 21-18 23 0" fill="${c.glass}" stroke="${c.dark}" stroke-width="3"/><path d="M42 48h17M39 62h23" stroke="${c.main}" stroke-width="5"/></g>`;
  return`${shadow}<g filter="url(#softShadow)"><path d="M45 77V52" stroke="${c.dark}" stroke-width="8"/><circle cx="50" cy="38" r="22" fill="${c.accent}"/><circle cx="35" cy="48" r="15" fill="${c.main}"/><circle cx="64" cy="50" r="17" fill="${c.light}"/><circle cx="53" cy="26" r="14" fill="${c.glass}"/></g>`;
}

saveAll();
renderHome();
